version: '3.8'
networks: # to create a custom bridge
  abhibr111: 
services:
  abhiapp007:
    image: abhiciapp:v1 
    build: . 
    container_name: abhicic1
    ports:
    - "1125:80"
    restart: always 
    networks: # use bridge created above 
    - abhibr111
